FROM node:18-alpine

# ARG NODE_ENV
ARG NODE_ENV
ARG PORT
ARG SERVER_URL
ARG SDK_BACKEND_SECRET
ARG MEETING_PLATFORM_JWT_SECRET
# # # # Set environment variables
# ENV NODE_ENV=$NODE_ENV 

ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV SERVER_URL=$SERVER_URL
ENV SDK_BACKEND_SECRET=$SDK_BACKEND_SECRET
ENV MEETING_PLATFORM_JWT_SECRET=$MEETING_PLATFORM_JWT_SECRET
WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 5100

CMD ["npm", "run", "start"]